### ISSUE TITLE
Update to Cake.Core 0.26?

### ISSUE THREAD

**Issue by AndyBarnettCTM** [cake-contrib/Cake.Newman#10]
I just tried to use this addin and my Cake tells me:
`Error: The assembly 'Cake.Newman, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.17.0). 
This assembly need to reference at least Cake.Core version 0.26.0. `

Does this mean that this addin needs to be updated? I'd like to use it and downgrading my Cake version to 0.17 isn't an option for me.

**Comment by gep13** [comment]
@AndyBarnettCTM yes, due to the breaking changes that were made in 0.26.0, this addin would need to be updated for it to work, without manual intervention.

You have the option of trying the suggestion that you would have seen in the error message that was outputted, as there is a good chance that the addin will just work.

**Comment by AndyBarnettCTM** [comment]
Correct me if I'm wrong, but if it requires 0.17.0, does that mean the November 2016 release of Cake? (https://cakebuild.net/blog/archive/2016/11/) I'm confused because there have been further commits to this repo in Jan 2017

**Comment by gep13** [comment]
That question would best be answered by @agc93

**Comment by agc93** [comment]
Sorry about the delays everyone! I somehow missed the notifications for the conversations 😢 

I'm going to be updating this repo to use 0.26 as part of #9 , but it still needs some work (build and packaging are broken).

I'll try and get some time, but it's a holiday weekend here, so may not be until next week.

**Comment by nmbro** [comment]
@agc93 I have continued #9 in my pull request of #11

**Comment by gep13** [comment]
@AndyBarnettCTM @agc93 @nmbro with the release of 0.3.0 I believe that this has been done, and can therefore be closed.

**Comment by AndyBarnettCTM** [comment]
cheers for the hard work everyone!
